=== Alexcr0103/EjerciciosLMSGI/Capítulo04-DTD/Exámenes/Examen.dtd
<!ELEMENT Familia (primergrado+,segundogrado*,parentesco?,estadocivil?)*>

<!ENTITY % datosfamiliar  "nombre CDATA #REQUIRED
                           codigo ID #REQUIRED 
                           relaciÃ³n (buena | mala | normal) #IMPLIED
                           edad CDATA #REQUIRED
                           contacto CDATA #IMPLIED">

<!ELEMENT primergrado EMPTY>
 <!ATTLIST primergrado %datosfamiliar;>
 
<!ELEMENT segundogrado EMPTY>
 <!ATTLIST segundogrado %datosfamiliar;
                        estado CDATA #FIXED "casado">

<!ELEMENT estadocivil (soltero|casado)>
<!ELEMENT soltero (#PCDATA)>
<!ELEMENT casado EMPTY>

<!ELEMENT parentesco (#PCDATA | padres | hermanos| primo)*>
  <!ELEMENT padres (padre,madre?)>
  <!ELEMENT padre EMPTY>
  <!ATTLIST padre codigo IDREFS #REQUIRED>
  <!ELEMENT madre EMPTY>
  <!ATTLIST madre codigo IDREFS #REQUIRED>
  <!ELEMENT hermanos (hermanosangre+, (hermanopolitico |hermanastro))>
  <!ELEMENT hermanosangre EMPTY>
  <!ATTLIST hermanosangre codigo IDREFS #REQUIRED>
  <!ELEMENT hermanopolitico EMPTY>
  <!ELEMENT hermanastro EMPTY>

  <!ELEMENT primo EMPTY>

=== Alexcr0103/EjerciciosLMSGI/Capítulo04-DTD/Exámenes/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Familia SYSTEM "Examen.dtd">

<Familia>
    <primergrado nombre="Antonio" codigo="A1" relación="mala" edad="57" contacto="nulo"/>
    <primergrado nombre="Loli" codigo="L1" relación="normal" edad="56"/>
    <primergrado nombre="Toni" codigo="T1" relación="buena" edad="30"/>
    <segundogrado nombre="Isabel" codigo="I1" relación="buena" edad="54"/>
    <segundogrado nombre="Celia" codigo="C1" relación="mala" edad="47" estado="casado"/>    
    <parentesco>De primer a segundo grado
        <padres>
            <padre codigo="A1" />
            <madre codigo="L1"/>
        </padres>
        <hermanos>
            <hermanosangre codigo="T1"/>
            <hermanopolitico/>
        </hermanos>
        <primo/>
    </parentesco>
    <estadocivil>
        <casado></casado>
    </estadocivil>
</Familia>
