=== Alexcr0103/EjerciciosLMSGI/Capítulo04-DTD/EjerciciosXmlPropio/DragonBall.dtd
<!ELEMENT DragonBall (heroe+,villano*,tipoPersonaje?,medio?)*>

<!ENTITY % datospersonaje "nombre ID #REQUIRED
                           superpoder (kamehameha | puÃ±etazo | ira) #IMPLIED
                           nemesis IDREF #IMPLIED
                           amigos IDREFS #IMPLIED">

<!ELEMENT heroe EMPTY>
 <!ATTLIST heroe %datospersonaje;>
 
<!ELEMENT villano EMPTY>
 <!ATTLIST villano %datospersonaje;
                   estado CDATA #FIXED "vivo">


<!ELEMENT tipoPersonaje (Saiyayin)>
<!ELEMENT Saiyayin (#PCDATA)>

<!ELEMENT medio (#PCDATA | manga | anime)*>
  <!ELEMENT anime (DragonBallZ+, (DragonBallGT |DragonBallSuper))>
  <!ELEMENT DragonBallZ EMPTY>
  <!ELEMENT DragonBallGT EMPTY>
  <!ELEMENT DragonBallSuper EMPTY>

  <!ELEMENT manga EMPTY>

=== Alexcr0103/EjerciciosLMSGI/Capítulo04-DTD/EjerciciosXmlPropio/XMLDTD/DragonBall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DragonBall SYSTEM "DragonBall.dtd">

<DragonBall>
    <heroe nombre="Goku" superpoder="kamehameha" nemesis="Freezer" amigos="Gohan Pan"/>
    <heroe nombre="Pan" superpoder="puñetazo" nemesis="Celula"/>
    <heroe nombre="Gohan" superpoder="puñetazo" nemesis="Celula"/>

    <villano nombre="Freezer" superpoder="ira" nemesis="Goku"/>
    <villano nombre="Celula" superpoder="ira" nemesis="Pan" estado="vivo"/>

    <tipoPersonaje>
        <Saiyayin>Goku Pan Goahn</Saiyayin>
    </tipoPersonaje>
    
    <medio>He visto la serie DragonBall
        <anime>
            <DragonBallZ />
            <DragonBallGT />
        </anime>
        <manga />
    </medio>
</DragonBall>
